name: lrpayne
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - numpy
  - pandas
  - scipy
  - matplotlib
  - scikit-learn
  - h5py
  - seaborn
  - astropy
  - lmfit
  - emcee
  - tensorflow=2.18
  - cudatoolkit=12.5
  - pip

